controllers:
    resource: ../src/Controller/
    type: annotation

app_routes:
    path: '/{any}'
    controller: App\Controller\ToolController::index
    requirements:
        any: '.+'

api_session_data:
    path: /api/session
    controller: App\Controller\ToolController::getSessionData

kernel:
    resource: ../src/Kernel.php
    type: annotation
